"""
Create a small synthetic word2sent.pkl for testing the training pipeline.
This generates a minimal dataset to verify the pipeline works.
"""
import pickle
import random

# Define a small vocabulary with example sentences
# Each word needs ~10-50 sentences for the small-scale test
word2sent = {
    # Common words with semantic meaning
    "computer": [
        "The computer is running slowly today.",
        "She bought a new computer for work.",
        "My computer crashed while I was writing.",
        "The computer science course was challenging.",
        "He fixed the broken computer himself.",
        "A quantum computer can solve complex problems.",
        "The computer screen flickered briefly.",
        "She learned to program on her first computer.",
        "The computer processes millions of calculations.",
        "We donated old computer equipment to schools.",
        "The computer industry has grown rapidly.",
        "Her computer skills improved significantly.",
        "The computer virus infected many systems.",
        "A powerful computer is needed for gaming.",
        "The computer lab was full of students.",
    ],
    "software": [
        "The software needs to be updated regularly.",
        "She develops software for mobile applications.",
        "This software is free to download.",
        "The software crashed unexpectedly yesterday.",
        "New software features were announced today.",
        "The software engineering team worked overtime.",
        "Installing the software took several minutes.",
        "The software license expires next month.",
        "Open source software has many contributors.",
        "The software bug caused data loss.",
        "Enterprise software is expensive to maintain.",
        "The software interface is user friendly.",
        "Security software protects against threats.",
        "The software update fixed several issues.",
        "Custom software was developed for them.",
    ],
    "data": [
        "The data was analyzed by researchers.",
        "She collected data from multiple sources.",
        "This data is confidential and protected.",
        "The data center uses renewable energy.",
        "Big data analytics reveals hidden patterns.",
        "The data scientist presented her findings.",
        "Raw data needs to be processed first.",
        "The data storage costs increased significantly.",
        "Accurate data is essential for decisions.",
        "The data breach affected millions of users.",
        "Historical data shows clear trends.",
        "The data visualization was impressive.",
        "Sensitive data must be encrypted.",
        "The data pipeline runs automatically.",
        "Real time data streaming is challenging.",
    ],
    "machine": [
        "The machine learning model improved accuracy.",
        "She operates the machine carefully.",
        "This machine is highly efficient.",
        "The machine broke down yesterday morning.",
        "A new machine was installed last week.",
        "The machine produces thousands of parts.",
        "Industrial machines require regular maintenance.",
        "The machine vision system detects defects.",
        "An old machine was replaced finally.",
        "The machine operates around the clock.",
        "Heavy machine parts were delivered today.",
        "The machine automatically adjusts settings.",
        "A complex machine needs skilled operators.",
        "The machine learning algorithm was trained.",
        "The machine hummed quietly in the corner.",
    ],
    "learning": [
        "Machine learning transforms many industries.",
        "She enjoys learning new programming languages.",
        "Deep learning requires large datasets.",
        "The learning curve was quite steep.",
        "Continuous learning is important for growth.",
        "Online learning became very popular recently.",
        "The learning process takes considerable time.",
        "Reinforcement learning solves complex problems.",
        "His learning style is very visual.",
        "The learning outcomes exceeded expectations.",
        "Active learning improves student engagement.",
        "Transfer learning saves training time.",
        "The learning experience was transformative.",
        "Self directed learning requires discipline.",
        "The learning algorithm converged quickly.",
    ],
    "model": [
        "The model achieved state of the art results.",
        "She trained a new model yesterday.",
        "This model is highly accurate.",
        "The language model generates coherent text.",
        "A pretrained model saves significant time.",
        "The model parameters were carefully tuned.",
        "The model predictions were surprisingly accurate.",
        "A smaller model runs much faster.",
        "The model architecture is transformer based.",
        "The model weights were saved to disk.",
        "The model performs well on benchmarks.",
        "A generative model creates new content.",
        "The model inference time was reduced.",
        "The model requires substantial compute resources.",
        "The model generalized well to new data.",
    ],
    "network": [
        "The neural network has many layers.",
        "She configured the network settings properly.",
        "This network is highly secure.",
        "The network connection was unstable.",
        "A social network connects millions of people.",
        "The network topology is quite complex.",
        "The network traffic increased significantly.",
        "A convolutional network processes images.",
        "The network latency was too high.",
        "The network infrastructure needs upgrading.",
        "A deep network can learn complex patterns.",
        "The network administrator fixed the issue.",
        "The network protocol ensures reliable delivery.",
        "A recurrent network handles sequences well.",
        "The network performance improved dramatically.",
    ],
    "algorithm": [
        "The algorithm runs in linear time.",
        "She implemented a new algorithm today.",
        "This algorithm is highly efficient.",
        "The sorting algorithm was optimized.",
        "A genetic algorithm finds good solutions.",
        "The algorithm complexity was carefully analyzed.",
        "The search algorithm found the best path.",
        "An iterative algorithm converges slowly.",
        "The algorithm handles edge cases properly.",
        "The algorithm was parallelized for speed.",
        "A greedy algorithm makes local decisions.",
        "The algorithm produces consistent results.",
        "The algorithm pseudocode was clear.",
        "A recursive algorithm can cause stack overflow.",
        "The algorithm documentation was thorough.",
    ],
    "training": [
        "The training process took several days.",
        "She supervised the training session carefully.",
        "This training dataset is very large.",
        "Model training requires significant compute.",
        "The training loss decreased steadily.",
        "Distributed training speeds up the process.",
        "The training examples were carefully selected.",
        "The training accuracy reached ninety percent.",
        "Proper training prevents overfitting issues.",
        "The training pipeline is fully automated.",
        "The training hyperparameters were tuned.",
        "Online training updates the model continuously.",
        "The training curriculum was well designed.",
        "The training infrastructure is cloud based.",
        "The training job completed successfully.",
    ],
    "embedding": [
        "Word embedding captures semantic meaning.",
        "She visualized the embedding space nicely.",
        "This embedding is very high dimensional.",
        "The embedding layer learns representations.",
        "A pretrained embedding improves performance.",
        "The embedding similarity was calculated.",
        "Static embedding is computationally efficient.",
        "The embedding vectors were normalized.",
        "Contextual embedding varies by context.",
        "The embedding dimension is two fifty six.",
        "The embedding quality affects downstream tasks.",
        "Sentence embedding represents entire sentences.",
        "The embedding lookup is very fast.",
        "The embedding model was finetuned.",
        "The embedding space clusters similar words.",
    ],
    "sentence": [
        "The sentence was grammatically correct.",
        "She wrote a complex sentence carefully.",
        "This sentence contains important information.",
        "The sentence structure is quite simple.",
        "A long sentence can be hard to parse.",
        "The sentence meaning was ambiguous.",
        "The sentence embedding captured semantics.",
        "The sentence boundary was detected.",
        "A complete sentence needs a subject.",
        "The sentence similarity score was high.",
        "The sentence transformer model performed well.",
        "The sentence classification task was easy.",
        "The sentence length affects processing time.",
        "A declarative sentence states a fact.",
        "The sentence tokenization was accurate.",
    ],
    "word": [
        "The word appears frequently in text.",
        "She looked up the word definition.",
        "This word has multiple meanings.",
        "The word embedding was computed.",
        "A compound word combines two roots.",
        "The word frequency analysis was helpful.",
        "The word vector has high dimensions.",
        "The word segmentation is language specific.",
        "A stopword is filtered during processing.",
        "The word similarity was calculated.",
        "The word context affects its meaning.",
        "The word tokenization split sentences.",
        "A rare word may have poor embeddings.",
        "The word sense disambiguation was challenging.",
        "The word list contained common terms.",
    ],
    "text": [
        "The text was analyzed for sentiment.",
        "She processed large amounts of text.",
        "This text is in English language.",
        "The text classification model worked well.",
        "Plain text files are easy to process.",
        "The text mining revealed interesting patterns.",
        "The text generation model is creative.",
        "The text preprocessing steps are important.",
        "Scientific text uses formal language.",
        "The text similarity was measured accurately.",
        "The text encoding used unicode format.",
        "The text summarization was concise.",
        "The text corpus was very large.",
        "The text normalization improved consistency.",
        "The text retrieval system was fast.",
    ],
    "language": [
        "The language model generates fluent text.",
        "She speaks multiple languages fluently.",
        "This language is widely spoken.",
        "The programming language is easy to learn.",
        "Natural language processing is advancing rapidly.",
        "The language understanding task is difficult.",
        "A formal language has strict rules.",
        "The language translation was accurate.",
        "The language detection worked correctly.",
        "Multiple language support was added.",
        "The language barrier was overcome.",
        "The language representation was learned.",
        "Sign language uses visual communication.",
        "The language syntax is quite complex.",
        "The language vocabulary keeps expanding.",
    ],
    "semantic": [
        "The semantic similarity was very high.",
        "She studied semantic relationships carefully.",
        "This semantic representation is rich.",
        "The semantic analysis revealed meaning.",
        "A semantic web links related concepts.",
        "The semantic embedding captured nuance.",
        "The semantic search found relevant results.",
        "The semantic parsing was successful.",
        "The semantic role labeling was accurate.",
        "The semantic vector space was explored.",
        "The semantic features were extracted.",
        "The semantic distance was computed.",
        "The semantic knowledge graph is useful.",
        "The semantic understanding improved significantly.",
        "The semantic segmentation labeled pixels.",
    ],
}

# Save to pickle file
output_path = "/home/user/swe4semantics/data/word2sent_small.pkl"
import os
os.makedirs("/home/user/swe4semantics/data", exist_ok=True)

with open(output_path, 'wb') as f:
    pickle.dump(word2sent, f)

print(f"Created synthetic dataset with {len(word2sent)} words")
print(f"Each word has ~{len(word2sent['computer'])} example sentences")
print(f"Saved to {output_path}")

# Also create a simple test sentences file for PCA
test_sentences = []
for word, sents in word2sent.items():
    test_sentences.extend(sents)

with open("/home/user/swe4semantics/data/test_sentences.txt", 'w') as f:
    for sent in test_sentences:
        f.write(sent + "\n")

print(f"Saved {len(test_sentences)} test sentences")
